### ISSUE TITLE
Setup.py fails due to mismatch in expected module name and actual module name

### ISSUE THREAD

**Issue by joonas** [coordt/django-elrte#1]
Running:

```
pip install git+http://github.com/coordt/django-elrte.git
```

Resulted in the following:

```
Downloading/unpacking git+http://github.com/coordt/django-elrte.git
  Cloning Git repository http://github.com/coordt/django-elrte.git to /var/folders/C4/C4AiFILGHwKqQJVJmfZ8ok+++TI/-Tmp-/pip-nA1wN7-build
  Running setup.py egg_info for package from git+http://github.com/coordt/django-elrte.git
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/var/folders/C4/C4AiFILGHwKqQJVJmfZ8ok+++TI/-Tmp-/pip-nA1wN7-build/setup.py", line 14, in <module>
        version = __import__('django-elrte').get_version().replace(' ', '-'),
    ImportError: No module named django-elrte
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/var/folders/C4/C4AiFILGHwKqQJVJmfZ8ok+++TI/-Tmp-/pip-nA1wN7-build/setup.py", line 14, in <module>

    version = __import__('django-elrte').get_version().replace(' ', '-'),

ImportError: No module named django-elrte
```

This can be easily remedied by modifying the version line in setup.py file to the following:

```
version = __import__('elrte').get_version().replace(' ', '-'),
```

instead of

```
version = __import__('django-elrte').get_version().replace(' ', '-'),
```

**Comment by coordt** [comment]
Fixed it. Thanks for alerting me!
